### PR TITLE
Handle missing or invalid newsletter book URL

### PR DESCRIPTION
**Pull request by juzim**
The apps script clears the URL in the sheet if none is found.

### CODE REVIEW

**Comment by niqdev** [comment]
I just pulled your latest change, i deleted the download file with the url from the config, but the newsletter is not downloaded anymore, is this right?
Before do any other pull, please rebase your master branch with my changes.

**Comment by juzim** [comment]
The newsletter also points to the current trial offer. I updated the
notification/logging for this case in this commit.

niqdev <notifications@github.com> schrieb am Sa., 17. Dez. 2016, 12:24:

**Comment by niqdev** [comment]
:+1:

**Comment by niqdev** [comment]
So did you modify also the source in the App Script? Now the url will be added only the first time that there is a new newsletter? Correct?

**Comment by juzim** [comment]
It parsed the current newsletter, adds the link to the free book to the
sheet and archives the mail. If there is no valid link, the sheet is empty
(I thought it would just crash).

niqdev <notifications@github.com> schrieb am Sa., 17. Dez. 2016, 13:50:

**Pull request merged**
