### PR TITLE
Absolute paths

### PR DESCRIPTION
**Pull request by juzim**
This should fix all issues with cron.

### CODE REVIEW

**Comment by niqdev** [comment]
The only conflict is this, which one is the correct?
```
<<<<<<< absolute-paths
            handleClaim(packpub, args, config, dir_path)
=======
            handleClaim(packpub, args, config)
        except NoBookException as e:
            log_info('[*] ' + e.message)
>>>>>>> master
```

**Comment by niqdev** [comment]
I think is the one with 4 params, should I keep the `NoBookException` ?
```
try:
            packpub.runDaily()
<<<<<<< absolute-paths
            handleClaim(packpub, args, config, dir_path)
=======
            handleClaim(packpub, args, config)
        except NoBookException as e:
            log_info('[*] ' + e.message)
>>>>>>> master
        except Exception as e:
            log_debug(e)
            if args.notify:
                Notify(config, None, None, args.notify).sendError(e, 'daily')
            return
```

**Comment by niqdev** [comment]
I think is like this, can you just confirm?
```
try:
            packpub.runDaily()
            handleClaim(packpub, args, config, dir_path)
        except NoBookException as e:
            log_info('[*] ' + e.message)
        except Exception as e:
            log_debug(e)
            if args.notify:
                Notify(config, None, None, args.notify).sendError(e, 'daily')
            return
```

**Comment by juzim** [comment]
Perfect :)

niqdev <notifications@github.com> schrieb am Fr., 16. Dez. 2016, 22:59:

**Comment by niqdev** [comment]
Do you have any idea why I can't see your name @juzim among the contributors?

**Comment by juzim** [comment]
Maybe the rebase messed it up. I tried to keep all three features in sync,
I guess that's how I pay for it.

niqdev <notifications@github.com> schrieb am Fr., 16. Dez. 2016, 23:19:

**Comment by niqdev** [comment]
About the merge, when you have time, just check if everything works fine (at least the configuration that you have added). I'll do the same.
About the contributions, I think you have something in your settings that block your visibility (I can't see your picture in the commits also)

**Comment by juzim** [comment]
Oh my god, thanks for telling me about contributors! I never bothered to look and was still using my work email in the config. So many contributions lost…

**Comment by niqdev** [comment]
:+1:

**Pull request merged**
