### PR TITLE
Adding support of Google Drive folder

### PR DESCRIPTION
**Pull request by windhamwong**
The script now supports Google Drive folder!
It will create a folder with name "packtpub" or specified in the config file.
The folder is also set to be shared.
The config line is printed on the screen to prompt user to add it back into the config file.
All the files are then uploaded to this folder.

a minor fix of message

### CODE REVIEW

**Comment by shaneog** [comment]
How would I use this to refer to sub-folders, e.g. `Books/packtpub` ?

**Comment by niqdev** [comment]
Hi @shaneog, what happen if you configure
```
googledrive.default_folder=Books/packtpub
googledrive.upload_folder=FOLDER_ID
```
You may need to create the root folder in advance

**Comment by shaneog** [comment]
Sadly it created a folder named "Books/packtpub" and not a folder named "packpub" inside the pre-existing folder "Books".

**Comment by juzim** [comment]
Could this be related  to
https://github.com/niqdev/packtpub-crawler/issues/57?

shaneog <notifications@github.com> schrieb am Mi., 8. März 2017, 20:36:

**Comment by niqdev** [comment]
I think is a bit tricky, I mean you need to have the id of the parent folder
See [this](http://stackoverflow.com/questions/13558653/how-can-i-create-a-new-folder-with-google-drive-api-in-python)

**Comment by juzim** [comment]
Ah, remote folders, nevermind.

niqdev <notifications@github.com> schrieb am Mi., 8. März 2017, 20:42:

**Pull request merged**
