### PR TITLE
Added cron example to readme

### PR DESCRIPTION
**Pull request by juzim**
Resolves https://github.com/niqdev/packtpub-crawler/issues/8

### CODE REVIEW

**Comment by niqdev** [comment]
That's fine, just before merge the request, does this work to you? Remember that yesterday I explain my issue and c&p the logs

**Comment by juzim** [comment]
Can you try changing the working directory first? 
`# m h  dom mon dow   command
00 09 * * * cd PATH/packtpub-crawler && /usr/bin/python PATH/packtpub-crawler/script/spider.py --config PATH/packtpub-crawler/config/prod.cfg --claimOnly --notify join >> /tmp/packtpub.log 2>&1
`

There seem to be issues with relative paths in python and cron.

Also, please pipe the output to a file so we can see what's happening in the script.

**Comment by niqdev** [comment]
I think there are some errors, the script doesn't work anymore now
```
[-] <type 'exceptions.AttributeError'> 'NoneType' object has no attribute 'select' | spider.py@90
Traceback (most recent call last):
  File "script/spider.py", line 90, in main
    run(packpub, args, config)
  File "script/spider.py", line 19, in run
    packpub.run()
  File "XXX/packtpub-crawler/script/packtpub.py", line 115, in run
    self.__POST_login()
  File "XXX/packtpub-crawler/script/packtpub.py", line 75, in __POST_login
    title = div_target.select('div.dotd-title > h2')[0].text.strip()
AttributeError: 'NoneType' object has no attribute 'select'
```

**Comment by niqdev** [comment]
The cron with this work anyway
```
*/2 * * * * cd XXX/packtpub-crawler && /usr/bin/python script/spider.py --config config/prod.cfg >> /tmp/packtpub.log 2>&1
```

**Comment by juzim** [comment]
I opened an issue about this today. There simply is no free book today but
some subscription offer instead. Hope this happens rarely but we should add
a better error message

niqdev <notifications@github.com> schrieb am Do., 15. Dez. 2016, 21:35:

**Pull request merged**
